touchscreen: fts_{521,spi}: Fix potential buffer overflow in fts_fwupdate_store
Fixes following errors:
../drivers/input/touchscreen/fts_521/fts.c:228:29: error: 'sscanf' may overflow; destination buffer in argument 3 has size 100, but the corresponding specifier may require size 101 [-Werror,-Wfortify-source]
  228 |         sscanf(buf, "%100s %d %d", path, &mode[0], &mode[1]);
      |                                    ^

../drivers/input/touchscreen/fts_spi/fts.c:247:29: error: 'sscanf' may overflow; destination buffer in argument 3 has size 100, but the corresponding specifier may require size 101 [-Werror,-Wfortify-source]
  247 |         sscanf(buf, "%100s %d %d", path, &mode[0], &mode[1]);
      |                                    ^

The above errors indicates that the `sscanf` function might overflow the
destination buffer `path` because the format specifier `%100s` could potentially
write a string of 100 characters plus a null terminator, exceeding the buffer
size of 100 characters.

So, to fix that simply increase the buffer size for path to 101 to accommodate
the null terminator.

Change-Id: I787ec6aa3e7b2b62484692852761e9eceef1735f
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>